resolver: lts-8.13

packages:
- '.'
- '../ipld'
- '../binary-serialise-cbor'

extra-deps:
- indentation-trifecta-0.0.1
- multihash-0.1.2
- base58-bytestring-0.1.0
- hedgehog-0.2.1
- bound-2
- list-extras-0.4.1.4
- wreq-0.5.0.1
- cabal-doctest-1.0.1

flags:
  binary-serialise-cbor:
    newtime15: true
